package utilitiesCalculator;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;

public class createDB {

	public static void main(String[] args) {
		
		final String DB_URL = "jdbc:derby:db/Tenant;create=true;";
		
		try{
			
			Connection conn = DriverManager.getConnection(DB_URL);
			
			Statement stmt = conn.createStatement();
			
//			try 
//			{
//				String dropTable = "drop table Tenant";
//				stmt.execute(dropTable);
//				System.out.println("Tenant table dropped.");
//			} catch (Exception e) {
//				
//				System.out.println("Tenant table does not exist");
//			}
			
			String createTableSQL = "CREATE TABLE Tenant"
					+ "(name varchar(100), "
					+ "address varchar(255),"
					+ "building varchar(100),"
					+ "rooms int,"
					+ "area double,"
					+ "numOfTenants int,"
					+ "occPeriod boolean,"
					+ "Tenant_ID int NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1),"
					+ "PRIMARY KEY(Tenant_ID)" + ")";
			
			stmt.execute(createTableSQL);
			
			System.out.println("Database has been created");
		}catch(SQLException e){
			System.out.println("Database already exists");
		}
	}
}
